/**
 * 剪取後x位文字...
 * (num,arr)
 */
var cutdownString=function(num,str)
{
   var number=str.length;//總長度....
   //num為需要cut走的長度......
   var a=str.substring(number-num)//取走不要的字符串

   str=str.replace(a,'');//換走....
   str=str+"..."
   /**
    * 頂...只系值傳遞..不是引用--fk...
    */
   return str;

}

//剪出函數...
//get函數...
export default cutdownString;
